In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/spam.csv'

data = pd.read_csv(file_url)


In [2]:
data.head()

target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
data['target'].unique()

array(['ham', 'spam'], dtype=object)

In [5]:
import string

string.punctuation # 특수문자 모음

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
sample_string = data['text'].loc[0] # 문자열 선택

for i in sample_string:
  print(i)

G
o
 
u
n
t
i
l
 
j
u
r
o
n
g
 
p
o
i
n
t
,
 
c
r
a
z
y
.
.
 
A
v
a
i
l
a
b
l
e
 
o
n
l
y
 
i
n
 
b
u
g
i
s
 
n
 
g
r
e
a
t
 
w
o
r
l
d
 
l
a
 
e
 
b
u
f
f
e
t
.
.
.
 
C
i
n
e
 
t
h
e
r
e
 
g
o
t
 
a
m
o
r
e
 
w
a
t
.
.
.


In [8]:
for i in sample_string: # 문자열의 문자를 하나씩 출력
  if i not in string.punctuation: # 특수 기호가 아닐경우 출력
    print(i)

G
o
 
u
n
t
i
l
 
j
u
r
o
n
g
 
p
o
i
n
t
 
c
r
a
z
y
 
A
v
a
i
l
a
b
l
e
 
o
n
l
y
 
i
n
 
b
u
g
i
s
 
n
 
g
r
e
a
t
 
w
o
r
l
d
 
l
a
 
e
 
b
u
f
f
e
t
 
C
i
n
e
 
t
h
e
r
e
 
g
o
t
 
a
m
o
r
e
 
w
a
t


In [10]:
# 특수기호 제외 글자 리스트 담기

new_string = []
for i in sample_string:
  if i not in string.punctuation:
    new_string.append(i)
    
new_string = ''.join(new_string) # 리스트를 문자열 형태로 변환

In [11]:
# remove function

def remove_punc(x):
  new_string = []
  for i in x:
    if i not in string.punctuation:
      new_string.append(i)
  new_string = ''.join(new_string)
  
  return new_string

In [15]:
# 한줄 한줄씩 함수 실행
data['text'] = data['text'].apply(remove_punc)

In [20]:
# 불용어 파악

# import nltk
# nltk.download('stopwords') # 불용어 가져오기
from nltk.corpus import stopwords

stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [21]:
for i in sample_string.split(): # 순회
  if i not in stopwords.words('english'): # 불용어가 아니면 소문자로 변환
    print(i.lower()) # 소문자로 출력

go
jurong
point,
crazy..
available
bugis
n
great
world
la
e
buffet...
cine
got
amore
wat...


In [22]:
new_string = []

for i in sample_string.split():
  if i.lower() not in stopwords.words('english'):
    new_string.append(i.lower())
    
new_string = ' '.join(new_string) # 공백 단위로 묶기

new_string

'go jurong point, crazy.. available bugis n great world la e buffet... cine got amore wat...'

In [24]:
def stop_words(x):
  new_string = []
  for i in x.split():
    if i.lower() not in stopwords.words('english'):
      # 소문자 변환 한것이 불용어가 아니면, 
      new_string.append(i.lower())
  new_string = ' '.join(new_string)
  
  return new_string



data['text'] = data['text'].apply(stop_words) # 텍스트에 stop_words 함수 적용
data['text']

0       go jurong point crazy available bugis n great ...
1                                 ok lar joking wif u oni
2       free entry 2 wkly comp win fa cup final tkts 2...
3                     u dun say early hor u c already say
4             nah dont think goes usf lives around though
                              ...                        
5569    2nd time tried 2 contact u u £750 pound prize ...
5570                          ü b going esplanade fr home
5571                          pity mood soany suggestions
5572    guy bitching acted like id interested buying s...
5573                                       rofl true name
Name: text, Length: 5574, dtype: object

In [25]:
data['target'] = data['target'].map({'spam':1, 'ham':0}) # text를 숫자로 변환

data['target']

0       0
1       0
2       1
3       0
4       0
       ..
5569    1
5570    0
5571    0
5572    0
5573    0
Name: target, Length: 5574, dtype: int64

In [27]:
x = data['text'] # 독립변수

y = data['target'] # 종속변수

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

cv.fit(x)

cv.vocabulary_

x = cv.transform(x)

print(x)

  (0, 1181)	1
  (0, 1414)	1
  (0, 1879)	1
  (0, 1881)	1
  (0, 2214)	1
  (0, 2497)	1
  (0, 3791)	1
  (0, 3848)	1
  (0, 3888)	1
  (0, 4687)	1
  (0, 4847)	1
  (0, 6433)	1
  (0, 8947)	1
  (0, 9184)	1
  (1, 4655)	1
  (1, 4886)	1
  (1, 5995)	1
  (1, 6027)	1
  (1, 9079)	1
  (2, 71)	1
  (2, 441)	1
  (2, 454)	1
  (2, 875)	1
  (2, 1267)	1
  (2, 2330)	1
  :	:
  (5570, 3188)	1
  (5570, 3564)	1
  (5570, 3810)	1
  (5570, 4188)	1
  (5571, 5566)	1
  (5571, 6359)	1
  (5571, 7611)	1
  (5571, 7986)	1
  (5572, 999)	1
  (5572, 1665)	1
  (5572, 1916)	1
  (5572, 3103)	1
  (5572, 3577)	1
  (5572, 3701)	1
  (5572, 3950)	1
  (5572, 4343)	1
  (5572, 4480)	1
  (5572, 5000)	1
  (5572, 5777)	1
  (5572, 7636)	1
  (5572, 8731)	1
  (5572, 8997)	1
  (5573, 5688)	1
  (5573, 7052)	1
  (5573, 8538)	1


In [47]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state= 100) # 학습셋 테스트셋 구분

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB() # 모델 객체 생성
model.fit(x_train, y_train) # 학습

pred = model.predict(x_test) # 예측

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [40]:
accuracy_score(y_test, pred)

0.9856502242152466

In [41]:
print(confusion_matrix(y_test, pred))

[[965  12]
 [  4 134]]


In [54]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB
# BernoulliNB()
bn = BernoulliNB()
bn.fit(x_train, y_train)
pred = bn.predict(x_test)

accuracy_score(y_test, pred)
confusion_matrix(y_test, pred)





array([[974,   3],
       [ 22, 116]], dtype=int64)

In [56]:
# GaussianNB()
gn = GaussianNB()
gn.fit(x_train.toarray(), y_train)
pred = gn.predict(x_test.toarray())

accuracy_score(y_test, pred)
confusion_matrix(y_test, pred)

array([[869, 108],
       [ 10, 128]], dtype=int64)